### ISSUE TITLE
Trello Integration

### ISSUE THREAD

**Issue by doinghun** [matteing/makerlog#1]
Hi, I revoked permission from Trello side as I wanted to change the board I integrate. 
It seems that Makerlog is not able to configure to the permission revoked from Trello. It's stuck at the "talking to Trello" page.

**Comment by matteing** [comment]
Thanks for the report.
I will fix that up right now, sorry about that! What's your username?

**Comment by doinghun** [comment]
Thanks for your reply! It's Mootda. Loving your work btw 👍

**Comment by matteing** [comment]
I just reset your Trello integration, try again. 😄 

Thanks!

**Comment by doinghun** [comment]
Works now. Thanks! :)

**Comment by nblackburn** [comment]
Probably an idea to close this as it seems to have been addressed. 😄
